### ISSUE TITLE
JsonTypeProvider build errors on Mono 4.3/FSharp 4.0

### ISSUE THREAD

**Issue by railcar88** [andagr/Firm#3]
I'm getting the following build errors related to the Data.fs file:
    .../Firm/src/Firm/Generator/Data.fs(18,23): error FS3033: The type provider 'ProviderImplementation.JsonProvider' reported an error: Object reference not set to an instance of an object
    .../Firm/src/Firm/Generator/Data.fs(18,23): error FS3033: The type provider 'ProviderImplementation.JsonProvider' reported an error: Object reference not set to an instance of an object
    .../Firm/src/Firm/Generator/Data.fs(51,41): error FS0039: The field, constructor or member 'Load' is not defined
    .../Firm/src/Firm/Generator/Data.fs(54,40): error FS0001: This expression was expected to have type    string list    but here has type    string []

**Comment by andagr** [comment]
Would it be possible to test with Fsharp 3.1? I had some issues with FSharp.Formatting 2.9.6 not generating popups with references with FSharp 4.0 on Windows.

**Comment by andagr** [comment]
This might be relevant, I suppose we could just try updating to the latest json provider. fsharp/FSharp.Data#823

**Comment by railcar88** [comment]
I'll test Firm with the upgraded FSharp.Data tonight as well. Thanks for doing the research.

**Comment by railcar88** [comment]
Upgrading FSharp.Data fixes the build for FSharp 4.0

**Comment by andagr** [comment]
Great, thanks for testing.

**Comment by railcar88** [comment]
My pleasure. Thanks for writing this library.
